#!/bin/sh /etc/rc.common
START=99

printMsg() {
    local msg="$1"
    logger -t "${PROGRAM}" "${msg}"
} 

restart(){                                                                                                       
  /usr/bin/fancts.sh &
  printMsg "The fan control module starts working！"
}

start(){
  /usr/bin/fancts.sh &
  printMsg "The fan control module starts working！"
}
