# by Manper 20250520

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-fancontrol-R3mini
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=Luci-fancontrol-R3mini
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+kmod-hwmon-pwmfan +kmod-hwmon-gpiofan

include $(TOPDIR)/feeds/luci/luci.mk

# $(eval $(call BuildPackage,luci-app-fancontrol-R3mini)
